### ISSUE TITLE
Typo : Quotations examples should be: one (two (three))

### ISSUE THREAD

**Issue by ntounsi** [w3c/eurlreq#27]
Paragraphe [3.11 Quotations](https://w3c.github.io/eurlreq/gap-analysis/latn-fr-gap#quotations)  in eurlreq documents

Examples cited are confusing.  
ერთი „ორი «სამი»“  or  ერთი „two «three»“

Should be one (two (three)) ?

**Comment by r12a** [comment]
@ntounsi, only the _text inside the q markup_ in that example is in English. So i think the examples are correct.  It is obviously an example you wouldn't expect to see.  Something more likely would be:

> Mais Lucy répondit: «Give George my love and tell him, ‹Muddle›».

So i'll close this.  Reopen if you think i missed something.
